[project]
name = "discogsworkflow"
version = "0.1.0"
description = "DiscogsWorkflow using crewAI"
authors = [{ name = "Simon Allocca", email = "simonallocca6@gmail.com" }]
requires-python = ">=3.11,<3.14"
dependencies = [
    "crewai[anthropic,tools]==1.9.3",
]

[project.scripts]
discogsworkflow = "discogsworkflow.main:run"
run_crew = "discogsworkflow.main:run"
train = "discogsworkflow.main:train"
replay = "discogsworkflow.main:replay"
test = "discogsworkflow.main:test"
run_with_trigger = "discogsworkflow.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
